name: Build iOS Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Theos Environment
        uses: Randomblock1/theos-action@v1
        with:
          theos-sdks: 'https://github.com/theos/sdks'

      - name: Fix Line Endings
        run: |
          brew install dos2unix
          dos2unix control

      - name: Compile the Tweak
        run: make package FINALPACKAGE=1

      - name: Upload .deb as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HaptiX-Rootless-Deb
          path: ${{ github.workspace }}/packages/*.deb
